In [27]:
import numpy as np

In [28]:
# 1. Create a NumPy array from the list [10, 20, 30, 40]

array1 = np.array([10, 20, 30, 40])
print("1:", array1)

1: [10 20 30 40]


In [29]:
# 2. Reshape the array np.array([2, 4, 6, 8, 10, 12, 14, 16])

a2 = np.array([2, 4, 6, 8, 10, 12, 14, 16])
array2_4_2 = a2.reshape(4, 2)
array2_2_4 = a2.reshape(2, 4)
print("2a (4,2):\n", array2_4_2)
print()
print("2b (2,4):\n", array2_2_4)

2a (4,2):
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]

2b (2,4):
 [[ 2  4  6  8]
 [10 12 14 16]]


In [7]:
# 3. a = np.array([[6, 7, 8, 9], [7, 8, 9, 10]])

a3 = np.array([[6, 7, 8, 9], [7, 8, 9, 10]])
print("3a shape:", a3.shape)
print("3b len:", len(a3))
print("3c ndim:", a3.ndim)
print("3d size:", a3.size)
print("3e dtype:", a3.dtype)

3a shape: (2, 4)
3b len: 2
3c ndim: 2
3d size: 8
3e dtype: int32


In [8]:
# 4. Create a 2×6 array filled with zeros

array4 = np.zeros((2, 6))
print("4:\n", array4)

4:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
# 5. Create a 3×3 array filled with ones

array5 = np.ones((3, 3))
print("5:\n", array5)

5:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# 6. Create a 5×2 array with random floats between 0 and 1

array6 = np.random.rand(5, 2)
print("6:\n", array6)

6:
 [[0.02312602 0.29124154]
 [0.4805246  0.1805883 ]
 [0.11391816 0.0199853 ]
 [0.01067596 0.83793287]
 [0.39733319 0.79113106]]


In [11]:
# 7. Create a 4×4 array with random integers between 50 and 150

array7 = np.random.randint(50, 151, size=(4, 4))
print("7:\n", array7)

7:
 [[ 63 149 145 122]
 [ 84 140  87  72]
 [ 79 114  88 150]
 [ 65 149 124 147]]


In [12]:
# 8. Using np.random.seed(7), generate a 2×5 array of random integers between 5 and 20

np.random.seed(7)
array8 = np.random.randint(5, 21, size=(2, 5))
print("8:\n", array8)

8:
 [[20  9 14 11  8]
 [ 8 12 12 17 14]]


In [13]:
# 9. Reshape the array from question 8 into shape (5, 2)

array9 = array8.reshape(5, 2)
print("9:\n", array9)

9:
 [[20  9]
 [14 11]
 [ 8  8]
 [12 12]
 [17 14]]


In [14]:
# 10. Create a 1D array of numbers from 5 to 25 with step size 5

array10 = np.arange(5, 26, 5)
print("10:", array10)

10: [ 5 10 15 20 25]


In [15]:
# 11. Create an array of 6 equally spaced numbers between -1 and 1

array11 = np.linspace(-1, 1, 6)
print("11:", array11)

11: [-1.  -0.6 -0.2  0.2  0.6  1. ]


In [16]:
# 12. a = np.array([2, 4, 6]) and b = np.array([1, 3, 5])

a12 = np.array([2, 4, 6])
b12 = np.array([1, 3, 5])
print("12a a+b:", a12 + b12)
print("12b a-b:", a12 - b12)
print("12c a*b:", a12 * b12)
print("12d a/b:", a12 / b12)
print("12e a**3:", a12 ** 3)

12a a+b: [ 3  7 11]
12b a-b: [1 1 1]
12c a*b: [ 2 12 30]
12d a/b: [2.         1.33333333 1.2       ]
12e a**3: [  8  64 216]


In [17]:
# 13. a = np.array([2, 4, 6, 100]), compute the mean

a13 = np.array([2, 4, 6, 100])
print("13 mean:", a13.mean())

13 mean: 28.0


In [18]:
# 14. From B = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

B14 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
print("14a row 2, col 1:", B14[2, 1])
print("14b all from col 0:", B14[:, 0])
print("14c all from row 2:", B14[2, :])

14a row 2, col 1: 16
14b all from col 0: [ 2  8 14]
14c all from row 2: [14 16 18]


In [19]:
# 15. *Bonus: Sort the array np.array([12, 4, 9, 1])

array15 = np.array([12, 4, 9, 1])
print("15 sorted:", np.sort(array15))

15 sorted: [ 1  4  9 12]


In [20]:
# 16. *Bonus: Sort S by rows and columns

S16 = np.array([[9, 7, 8], [3, 2, 1]])
print("16a sort rows:\n", np.sort(S16, axis=1))
print("16b sort cols:\n", np.sort(S16, axis=0))

16a sort rows:
 [[7 8 9]
 [1 2 3]]
16b sort cols:
 [[3 2 1]
 [9 7 8]]


In [21]:
# 17. 3×4 array of random ints 0-50, np.random.seed(11)

np.random.seed(11)
array17 = np.random.randint(0, 51, size=(3, 4))
print("17:\n", array17)

17:
 [[25 16 27 17]
 [13 12 33  7]
 [18 24 45 28]]


In [22]:
# 18. a = np.array([5, 15, 25, 35, 45]), extract all values greater than the mean

a18 = np.array([5, 15, 25, 35, 45])
mean18 = a18.mean()
print("18:", a18[a18 > mean18])

18: [35 45]


In [23]:
# 19. a = np.array([2, 4, 6, 8, 10, 12])

a19 = np.array([2, 4, 6, 8, 10, 12])
print("19a >5 and divisible by 4:", a19[(a19 > 5) & (a19 % 4 == 0)])
print("19b <5 or >9:", a19[(a19 < 5) | (a19 > 9)])
print("19c not >7:", a19[~(a19 > 7)])

19a >5 and divisible by 4: [ 8 12]
19b <5 or >9: [ 2  4 10 12]
19c not >7: [2 4 6]


In [24]:
# 20. a = np.array([42, 7, 19, 88])

a20 = np.array([42, 7, 19, 88])
print("20a min idx:", np.argmin(a20))
print("20b max idx:", np.argmax(a20))

20a min idx: 1
20b max idx: 3


In [25]:
# 21. *Bonus: From B = np.array([[12, 45, 7], [33, 5, 29]]), indices of min/max (1D + 2D)

B21 = np.array([[12, 45, 7], [33, 5, 29]])
min_1d = np.argmin(B21)
max_1d = np.argmax(B21)
min_2d = np.unravel_index(min_1d, B21.shape)
max_2d = np.unravel_index(max_1d, B21.shape)
print("21a min index 1D:", min_1d, "2D:", min_2d)
print("21b max index 1D:", max_1d, "2D:", max_2d)

21a min index 1D: 4 2D: (np.int32(1), np.int32(1))
21b max index 1D: 1 2D: (np.int32(0), np.int32(1))


In [26]:
# 22. *Bonus: Load and rotate image 90 degrees

try:
    from PIL import Image
    img = Image.open("images/numpy1.png")
    img_rotated = img.rotate(-90, expand=True)
    img_rotated.show()
    print("22: Image rotated (see output)")
except Exception as e:
    print("22: Image rotation failed (Pillow required or file missing):", e)

22: Image rotation failed (Pillow required or file missing): No module named 'PIL'
