In [4]:
import numpy as np

# 1. create a numpy array from the list [10, 20, 30, 40]
arr1 = np.array([10, 20, 30, 40])
print("1:", arr1)
print()

# 2. reshape the array np.array([2, 4, 6, 8, 10, 12, 14, 16]) into (4,2) and (2,4)
arr2 = np.array([2, 4, 6, 8, 10, 12, 14, 16])
arr2_4x2 = arr2.reshape(4, 2)
arr2_2x4 = arr2.reshape(2, 4)
print("2 (4x2):\n", arr2_4x2)
print("2 (2x4):\n", arr2_2x4)
print()

# 3. given a = np.array([[6, 7, 8, 9], [7, 8, 9, 10]]), print shape, len, ndim, size, dtype
a3 = np.array([[6, 7, 8, 9], [7, 8, 9, 10]])
print("3 shape:", a3.shape)
print("3 len:", len(a3))
print("3 ndim:", a3.ndim)
print("3 size:", a3.size)
print("3 dtype:", a3.dtype)
print()

# 4. create a 2x6 array filled with zeros
arr4 = np.zeros((2, 6))
print("4:\n", arr4)
print()

# 5. create a 3x3 array filled with ones
arr5 = np.ones((3, 3))
print("5:\n", arr5)
print()

# 6. create a 5x2 array with random floats between 0 and 1
arr6 = np.random.rand(5, 2)
print("6:\n", arr6)
print()

# 7. create a 4x4 array with random integers between 50 and 150
arr7 = np.random.randint(50, 151, (4, 4))
print("7:\n", arr7)
print()

# 8. using np.random.seed(7), generate a 2x5 array of random integers between 5 and 20
np.random.seed(7)
arr8 = np.random.randint(5, 21, (2, 5))
print("8:\n", arr8)
print()

# 9. reshape the array from question 8 into shape (5, 2)
arr9 = arr8.reshape(5, 2)
print("9:\n", arr9)
print()

# 10. create a 1d array of numbers from 5 to 25 with step size 5
arr10 = np.arange(5, 26, 5)
print("10:", arr10)
print()

# 11. create an array of 6 equally spaced numbers between -1 and 1
arr11 = np.linspace(-1, 1, 6)
print("11:", arr11)
print()

# 12. given a = np.array([2, 4, 6]) and b = np.array([1, 3, 5]), compute operations
a12 = np.array([2, 4, 6])
b12 = np.array([1, 3, 5])
print("12 a+b:", a12 + b12)
print("12 a-b:", a12 - b12)
print("12 a*b:", a12 * b12)
print("12 a/b:", a12 / b12)
print("12 a**3:", a12 ** 3)
print()

# 13. given a = np.array([2, 4, 6, 100]), compute the mean
a13 = np.array([2, 4, 6, 100])
print("13 mean:", np.mean(a13))
print()

# 14. from the array B = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]]), extract elements
B14 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
elem_row2_col1 = B14[2, 1]
col0 = B14[:, 0]
row2 = B14[2, :]
print("14 element row2,col1:", elem_row2_col1)
print("14 col0:", col0)
print("14 row2:", row2)
print()

# 17. generate a 3x4 array of random integers between 0 and 50 with np.random.seed(11)
np.random.seed(11)
arr17 = np.random.randint(0, 51, (3, 4))
print("17:\n", arr17)
print()

# 18. from a = np.array([5, 15, 25, 35, 45]), extract all values greater than the mean
a18 = np.array([5, 15, 25, 35, 45])
mean18 = np.mean(a18)
greater_than_mean = a18[a18 > mean18]
print("18:", greater_than_mean)
print()

# 19. given a = np.array([2, 4, 6, 8, 10, 12]), extract:
a19 = np.array([2, 4, 6, 8, 10, 12])
gt5_div4 = a19[(a19 > 5) & (a19 % 4 == 0)]  # elements greater than 5 and divisible by 4
lt5_gt9 = a19[(a19 < 5) | (a19 > 9)]        # elements less than 5 or greater than 9
not_gt7 = a19[~(a19 > 7)]                   # elements not greater than 7
print("19 greater than 5 and divisible by 4:", gt5_div4)
print("19 less than 5 or greater than 9:", lt5_gt9)
print("19 not greater than 7:", not_gt7)
print()

# 20. given a = np.array([42, 7, 19, 88]), find indices of min and max
a20 = np.array([42, 7, 19, 88])
idx_min = np.argmin(a20)
idx_max = np.argmax(a20)
print("20 index min:", idx_min)
print("20 index max:", idx_max)
print()

1: [10 20 30 40]

2 (4x2):
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
2 (2x4):
 [[ 2  4  6  8]
 [10 12 14 16]]

3 shape: (2, 4)
3 len: 2
3 ndim: 2
3 size: 8
3 dtype: int64

4:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

5:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

6:
 [[0.48737161 0.94180665]
 [0.85079509 0.72996447]
 [0.10873607 0.89390417]
 [0.85715425 0.16508662]
 [0.63233401 0.02048361]]

7:
 [[117 120  93 114]
 [129 146  73  77]
 [120 139  60 107]
 [ 77  94  64  57]]

8:
 [[20  9 14 11  8]
 [ 8 12 12 17 14]]

9:
 [[20  9]
 [14 11]
 [ 8  8]
 [12 12]
 [17 14]]

10: [ 5 10 15 20 25]

11: [-1.  -0.6 -0.2  0.2  0.6  1. ]

12 a+b: [ 3  7 11]
12 a-b: [1 1 1]
12 a*b: [ 2 12 30]
12 a/b: [2.         1.33333333 1.2       ]
12 a**3: [  8  64 216]

13 mean: 28.0

14 element row2,col1: 16
14 col0: [ 2  8 14]
14 row2: [14 16 18]

17:
 [[25 16 27 17]
 [13 12 33  7]
 [18 24 45 28]]

18: [35 45]

19 greater than 5 and divisible by 4: [ 8 12]
19 less than 5 or greater than 9: [ 2  4 10 12]
19 not greater t