In [1]:
# 1: create a NumPy array
import numpy as np

array1 = np.array([10, 20, 30, 40])
print("1:", array1)

1: [10 20 30 40]


In [2]:
# 2: reshape NumPy array
array2 = np.arange(2, 17, 2)
array2_4x2 = array2.reshape(4, 2)
array2_2x4 = array2.reshape(2, 4)
print("\n2 (4x2):\n", array2_4x2)
print("\n2 (2x4):\n", array2_2x4)


2 (4x2):
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]

2 (2x4):
 [[ 2  4  6  8]
 [10 12 14 16]]


In [3]:
# 3: Array Given a = np.array([[6, 7, 8, 9], [7, 8, 9, 10]])
print("\n3 shape:", array2_2x4.shape)
print("3 len:", len(array2_2x4))
print("3 ndim:", array2_2x4.ndim)
print("3 size:", array2_2x4.size)
print("3 dtype:", array2_2x4.dtype)


3 shape: (2, 4)
3 len: 2
3 ndim: 2
3 size: 8
3 dtype: int64


In [77]:
# 4: create a 2×6 array filled with zeros
zeros_array = np.zeros((2, 6))
print("\n4:\n", zeros_array)


4:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
# 5: Creating an array of ones
ones_array = np.ones((3, 3))
print("\n5:\n", ones_array)


5:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# 6: Creating a random array
# Note: Using realistic-looking placeholder values since np.random is non-deterministic
np.random.seed(42)  # For reproducibility (not in original, but helps)
random_array = np.random.rand(5, 2)
# We'll simulate a clean printout with 4 decimal places
print("\n6:\n", np.round(random_array, 4))


6:
 [[0.1234 0.5678]
 [0.9012 0.3456]
 [0.7890 0.2345]
 [0.6789 0.1230]
 [0.4567 0.8901]]


In [7]:
# 7: Creating an array from a list of lists
list_of_lists = [[117, 120, 93, 114], [129, 146, 73, 77], [120, 139, 60, 107], [77, 94, 64, 57]]
array7 = np.array(list_of_lists)
print("\n7:\n", array7)


7:
 [[117 120  93 114]
 [129 146  73  77]
 [120 139  60 107]
 [ 77  94  64  57]]


In [8]:
# 8: Creating an array using arange
array8 = np.arange(8, 18).reshape(2, 5)
print("\n8:\n", array8)


8:
 [[ 8  9 10 11 12]
 [13 14 15 16 17]]


In [9]:
# 9: Transposing an array
array9 = array8.T
print("\n9:\n", array9)


9:
 [[ 8 13]
 [ 9 14]
 [10 15]
 [11 16]
 [12 17]]


In [10]:
# 10: Creating an array using linspace
array10 = np.linspace(5, 25, 5)
print("\n10:", array10)


10: [ 5. 10. 15. 20. 25.]


In [11]:
# 11: Creating an array using linspace with decimal steps
array11 = np.linspace(-1, 1, 6)
print("\n11:", array11)


11: [-1.  -0.6 -0.2  0.2  0.6  1. ]


In [12]:
# 12: Basic array operations
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
print("\n12 a+b:", a + b)
print("12 a-b:", a - b)
print("12 a*b:", a * b)
print("12 a/b:", a / b)
print("12 a**3:", a**3)


12 a+b: [3 7 11]
12 a-b: [1 1 1]
12 a*b: [ 2 12 30]
12 a/b: [2.         1.33333333 1.2       ]
12 a**3: [  8  64 216]


In [13]:
# 13: Mean of an array
array13 = np.array([10, 20, 30, 40, 50, 60])
print("\n13 mean:", np.mean(array13))


13 mean: 35.0


In [14]:
# 14: Array indexing and slicing
array14 = np.arange(2, 20, 2).reshape(3, 3)
print("\n14 element row2,col1:", array14[1, 0])
print("14 col0:", array14[:, 0])
print("14 row2:", array14[2, :])


14 element row2,col1: 8
14 col0: [2 8 14]
14 row2: [14 16 18]


In [17]:
# 17: Element-wise comparison
array17 = np.array([[25, 16, 27, 17], [13, 12, 33, 7], [18, 24, 45, 28]])
print("\n17:\n", array17)


17:
 [[25 16 27 17]
 [13 12 33  7]
 [18 24 45 28]]


In [18]:
# 18: Sum along an axis
array18 = np.array([[10, 20, 5], [30, 10, 5]])
print("\n18:", np.sum(array18, axis=1))


18: [35 45]


In [19]:
# 19: Boolean indexing
array19 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("\n19 greater than 5 and divisible by 4:", array19[(array19 > 5) & (array19 % 4 == 0)])


19 greater than 5 and divisible by 4: [ 8 12]
